name: 'credit_risk_fraud_detection_dbt'
version: '1.0.0'

profile: 'credit_risk_fraud_detection_dbt'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  credit_risk_fraud_detection_dbt:
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: view
    marts:
      silver:
        +schema: silver
        +materialized: table
      gold:
        +schema: gold
        +materialized: table

snapshots:
  credit_risk_fraud_detection_dbt:
    +target_schema: silver