-- stg_transactions.sql
select
    cast(transaction_id as string)             as transaction_id,
    cast(customer_id as string)                as customer_id,
    cast(account_id as string)                 as account_id,
    cast(loan_account_id as string)            as loan_account_id,
    cast(transaction_type as string)           as transaction_type,
    cast(transaction_mode as string)           as transaction_mode,
    cast(amount as double)                     as amount,
    cast(currency as string)                   as currency,
    cast(transaction_date as date)             as transaction_date,
    cast(transaction_timestamp as timestamp)   as transaction_timestamp,
    cast(value_date as date)                   as value_date,
    cast(merchant_id as string)                as merchant_id,
    cast(merchant_name as string)              as merchant_name,
    cast(merchant_category_code as string)     as merchant_category_code,
    cast(merchant_category as string)          as merchant_category,
    cast(merchant_city as string)              as merchant_city,
    cast(merchant_state as string)             as merchant_state,
    cast(channel as string)                    as channel,
    cast(device_id as string)                  as device_id,
    cast(device_type as string)                as device_type,
    cast(customer_city_at_txn as string)       as customer_city_at_txn,
    cast(distance_from_home_km as double)      as distance_from_home_km,
    cast(account_balance_before as double)     as account_balance_before,
    cast(account_balance_after as double)      as account_balance_after,
    cast(upi_vpa as string)                    as upi_vpa,
    cast(beneficiary_account as string)        as beneficiary_account,
    cast(beneficiary_ifsc as string)           as beneficiary_ifsc,
    cast(beneficiary_name as string)           as beneficiary_name,
    cast(is_reversal as boolean)               as is_reversal,
    cast(original_txn_id as string)            as original_txn_id,
    cast(is_international as boolean)          as is_international,
    -- source-provided fraud features, kept but renamed _source — see
    -- int_transactions_features for the independently recomputed versions
    cast(velocity_1hr as int)                  as velocity_1hr_source,
    cast(velocity_24hr as int)                 as velocity_24hr_source,
    cast(amount_vs_30d_avg_ratio as double)    as amount_vs_30d_avg_ratio_source,
    cast(is_new_device as boolean)             as is_new_device_source,
    cast(is_new_merchant_category as boolean)  as is_new_merchant_category_source,
    cast(is_night_transaction as boolean)      as is_night_transaction_source,
    cast(time_since_last_txn_mins as double)   as time_since_last_txn_mins_source,
    cast(is_fraud as boolean)                  as is_fraud,
    cast(fraud_type as string)                 as fraud_type,
    cast(fraud_scenario_id as string)          as fraud_scenario_id,
    cast(created_at as timestamp)              as created_at
from {{ source('bronze', 'transactions') }}